mashulot_ombori = {
    'Combo Plus Isituvchan (Qora choy)':[16000,'uploads/combo_plus.jpg'],
    'FitCombo':[30000,'uploads/combo_fit.jpg'],
    "Iftar kofte grill mol go'shtidan":[35000,'uploads/iftar_kofte.jpg'],
    "Donar boks  mol go'shtidan":[34000,'uploads/donor_boks.jpg'],
    "Donar boks tovuq go'shtidan":[32000,'uploads/donor_boks_tovuq.jpg'],
    "COMBO+":[16000,'uploads/combo.jpg'],
    "Iftar strips tovuq go'shtidan":[30000,'uploads/iftar_strips.jpg'],
    "Kids COMBO":[16000,'uploads/kids.jpg'],
    "Mol goʼshtidan qalampir lavash":[26000,'uploads/mol.jpg'],
    "Tovuq goʼshtli qalampir lavash":[24000,'uploads/tovuq.jpg'],
    "Mol goʼshtidan pishloqli lavash Standard":[25000,'uploads/mol_pishloqli.jpg'],
    "Lavash cheese tovuq go'sht Standart":[23000,'uploads/lavash_cheese.jpg'],
    "FITTER":[22000,'FITTER'],
    "Lavash tovuq go'sht":[20000,'uploads/lavash_tovuq.jpg'],
    "Lavash mol go'sht":[25000,'uploads/lavash_mol.jpg'],
    "Shaurma qalampir mol go'sht":[26000,'uploads/shaurma_qalampir_mol.jpg'],
    "Shaurma tovuq go'sht":[24000,'uploads/shaurma_tovuq.jpg'],
    "Shaurma qalampir tovuq go'sht":[21000,'uploads/shaurma_qalampir_tovuq.jpg'],
    "Shaurma mol go'sht":[25000,'uploads/shaurma_mol.jpg'],
    "Gamburger":[22000,'uploads/gamburger.jpg'],
    "Double burger":[33000,'uploads/double_burger.jpg'],
    "Cheese burger":[24000,'uploads/cheese_burger.jpg'],
    "Double cheese":[37000,'uploads/double_cheese.jpg'],
    "Hot-dog baguette":[25000,'uploads/hot_dog.jpg'],
    "Sub tovuq cheese":[21000,'uploads/sub_tovuq_cheese.jpg'],
    "Sub tovuq":[19000,'uploads/sub_tovuq.jpg'],
    "Hot-dog baguette double":[30000,'uploads/hot_dog_double.jpg'],
    "Hot-dog kids":[17000,'uploads/hot_dog_kids.jpg'],
    "Sub go'sht cheese":[23000,'uploads/sub_gosht_cheese.jpg'],
    "Hot-dog classic":[20000,'uploads/hot_dog_classic.jpg'],
    "Sub go'sht":[18000,'uploads/sub_gosht_.jpg'],
    "Sok dena 0,33l":[12000,'uploads/sok_dena.jpg'],
    "Pepsi 1,5":[13000,'uploads/pepsi_1.jpg'],
    "Suv 0,5":[5000,'uploads/suv_05.jpg'],
    "Pepsi 0,5":[8000,'uploads/pepsi_05.jpg'],
    "Quyib beriladigan Pepsi":[11000,'uploads/quyib_pepsi.jpg'],
    "Bliss sharbati":[17000,'uploads/bliss_sharbati.jpg'],
    "Amerikano":[16000,'uploads/amerikano.jpg'],
    "Latte":[14000,'uploads/latte.jpg'],
    "Ko'k choy":[4000,'uploads/kok_choy.jpg'],
    "Qora_choy":[5000,'uploads/qora_choy.jpg'],
    "Limonli ko'k choy":[4000,'uploads/limonli_choy.jpg'],
    "Medovik Asalim":[16000,'uploads/medovik_asal.jpg'],
    "Chizkeyk":[16000,'uploads/chizkeyk.jpg'],
    "Donut karameli":[18000,'uploads/donut_karameli.jpg'],
    "Donut mevali":[17000,'uploads/donut_mevali.jpg'],
    "Ketchup":[5000,'uploads/ketchup.jpg'],
    "Guruchi":[7000,'uploads/guruch.jpg'],
    "Sarimsoqli_qayla":[8000,'uploads/sarimsoqli_qayla.jpg'],
    "chili_qaylasi":[10000,'uploads/chili_qaylasi.jpg'],
    "Mayonez":[4000,'uploads/mayonez.jpg'],
    "Salat":[12000,'uploads/salat.jpg'],
    "Po-derevenski":[13000,'uploads/poderevenski.jpg'],
    "Tovuq Strips":[19000,'uploads/tovuq_strips.jpg'],
    "Fri":[6000,'uploads/fri.jpg'],
}